package de.hft_stuttgart.ip1.client;

import de.hft_stuttgart.ip1.client.actions.DirectAction;
import de.hft_stuttgart.ip1.client.actions.ExitAction;
import de.hft_stuttgart.ip1.client.actions.LoginAction;
import de.hft_stuttgart.ip1.client.actions.LogoutAction;
import de.hft_stuttgart.ip1.client.gui.SudokuPanel;
import de.hft_stuttgart.ip1.common.Session;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.rmi.RemoteException;


public class MainFrame extends JFrame {

    private JPanel contentPane;
    private JButton a1Button;
    private JButton a2Button;
    private JButton a3Button;
    private JButton a4Button;
    private JButton a5Button;
    private JButton a6Button;
    private JButton a7Button;
    private JButton a8Button;
    private JButton a9Button;


    private JPanel sudokuPanel;
    private JPanel upperPane;
    private JPanel lowerPane;
    private JButton button1;
    private JButton button2;
    private JButton button3;
    private JButton button4;
    private JButton button5;
    private JButton button6;
    private JButton button7;
    private JButton button8;
    private JButton button9;
    private JButton button10;
    private JButton button11;
    private JButton button12;
    private JButton button13;
    private JButton button14;
    private JButton button15;
    private JButton button16;


    private int[] grid;
    private Session session;
    private int sudSize;
    public MainFrame(Session session, int sudSize, int[] grid) throws RemoteException {
        this.session = session;
        this.grid = grid;
        this.sudSize = sudSize;
        $$$setupUI$$$();
        setContentPane($$$getRootComponent$$$());
        pack();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        JMenuBar menuBar = new JMenuBar();
        setJMenuBar(menuBar);
        // NOI18N
        JMenu menu = new JMenu("Menu");
        menuBar.add(menu);
        menu.add(new LoginAction(MainFrame.this));
        menu.add(new LogoutAction(MainFrame.this));
        menu.add(new JSeparator());
        menu.add(new ExitAction(MainFrame.this));
        menuBar.add(new JMenuItem(new DirectAction(MainFrame.this)));
        a1Button.setAction(new ButtonAction(1));
        a2Button.setAction(new ButtonAction(2));
        a3Button.setAction(new ButtonAction(3));
        a4Button.setAction(new ButtonAction(4));
        a5Button.setAction(new ButtonAction(5));
        a6Button.setAction(new ButtonAction(6));
        a7Button.setAction(new ButtonAction(7));
        a8Button.setAction(new ButtonAction(8));
        a9Button.setAction(new ButtonAction(9));
        button1.setAction(new ButtonAction(10));
        button2.setAction(new ButtonAction(11));
        button3.setAction(new ButtonAction(12));
        button4.setAction(new ButtonAction(13));
        button5.setAction(new ButtonAction(14));
        button6.setAction(new ButtonAction(15));
        button7.setAction(new ButtonAction(16));
        button8.setAction(new ButtonAction(17));
        button9.setAction(new ButtonAction(18));
        button10.setAction(new ButtonAction(19));
        button11.setAction(new ButtonAction(20));
        button12.setAction(new ButtonAction(21));
        button13.setAction(new ButtonAction(22));
        button14.setAction(new ButtonAction(23));
        button15.setAction(new ButtonAction(24));
        button16.setAction(new ButtonAction(25));

        System.out.println(session.getGames());

    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        contentPane.setMinimumSize(new Dimension(480, 320));
        contentPane.setPreferredSize(new Dimension(480, 320));
        upperPane = new JPanel();
        upperPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(upperPane, BorderLayout.CENTER);
        upperPane.add(sudokuPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        sudokuPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createRaisedBevelBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        lowerPane = new JPanel();
        lowerPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 10, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(lowerPane, BorderLayout.SOUTH);
        a1Button = new JButton();
        a1Button.setText("1");
        lowerPane.add(a1Button, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        lowerPane.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(0, 9, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        a2Button = new JButton();
        a2Button.setText("2");
        lowerPane.add(a2Button, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        a3Button = new JButton();
        a3Button.setText("3");
        lowerPane.add(a3Button, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        a4Button = new JButton();
        a4Button.setText("4");
        lowerPane.add(a4Button, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        a5Button = new JButton();
        a5Button.setText("5");
        lowerPane.add(a5Button, new com.intellij.uiDesigner.core.GridConstraints(0, 4, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        a6Button = new JButton();
        a6Button.setText("6");
        lowerPane.add(a6Button, new com.intellij.uiDesigner.core.GridConstraints(0, 5, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        a7Button = new JButton();
        a7Button.setText("7");
        lowerPane.add(a7Button, new com.intellij.uiDesigner.core.GridConstraints(0, 6, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        a8Button = new JButton();
        a8Button.setText("8");
        lowerPane.add(a8Button, new com.intellij.uiDesigner.core.GridConstraints(0, 7, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        a9Button = new JButton();
        a9Button.setText("9");
        lowerPane.add(a9Button, new com.intellij.uiDesigner.core.GridConstraints(0, 8, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));

        button1 = new JButton();
        button1.setText("a");
        lowerPane.add(button1);

        button2 = new JButton();
        button2.setText("b");
        lowerPane.add(button2);

        button3 = new JButton();
        button3.setText("c");
        lowerPane.add(button3);

        button4 = new JButton();
        button4.setText("d");
        lowerPane.add(button4);

        button5 = new JButton();
        button5.setText("e");
        lowerPane.add(button5);

        button6 = new JButton();
        button6.setText("f");
        lowerPane.add(button6);

        button7 = new JButton();
        button7.setText("g");
        lowerPane.add(button7);

        button8 = new JButton();
        button8.setText("h");
        lowerPane.add(button8);

        button9 = new JButton();
        button9.setText("i");
        lowerPane.add(button9);

        button10 = new JButton();
        button10.setText("j");
        lowerPane.add(button10);

        button11 = new JButton();
        button11.setText("k");
        lowerPane.add(button11);


        button12 = new JButton();
        button12.setText("l");
        lowerPane.add(button12);

        button13 = new JButton();
        button13.setText("m");
        lowerPane.add(button13);

        button14 = new JButton();
        button14.setText("n");
        lowerPane.add(button14);

        button15 = new JButton();
        button15.setText("o");
        lowerPane.add(button15);

        button16 = new JButton();
        button16.setText("p");
        lowerPane.add(button16);

    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code her

        sudokuPanel = new SudokuPanel(upperPane, sudSize, session, grid);
    }

    private class ButtonAction extends AbstractAction {
        private final int c;

        public ButtonAction(int value) {

            this.c = value;
        }

        @Override
        public void actionPerformed(ActionEvent actionEvent) {
            try {
                ((SudokuPanel) sudokuPanel).setData(c);
            } catch (RemoteException e) {
                throw new RuntimeException(e);
            }
        }
    }
}
